const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto')
const{createLiveDraftAdapter,liveDraftPayload,validateLiveManifest}=require('../lib/paypal-live-drafts.ts')
const p={reference:'AH-A6-B145',buyerName:'Synthetic Buyer',recipientEmail:'fixture@example.invalid',address:{address_line_1:'1 Synthetic St',admin_area_2:'Example',admin_area_1:'CA',postal_code:'90045',country_code:'US'},items:[{name:'Synthetic item',quantity:2,unitCents:750}],subtotalCents:1500,discountCents:0,shippingCents:500,dueCents:2000}
const config={clientId:'SYNTHETIC',clientSecret:'SYNTHETIC',merchantEmail:'merchant@example.invalid',anchorId:'INV2-BNTD-CBFA-YHPK-YRP5',enabled:true}
function inv(plan=p){return{...liveDraftPayload(plan,config.merchantEmail),id:'INV2-SYNTHETIC-0001',status:'DRAFT',amount:{currency_code:'USD',value:(plan.dueCents/100).toFixed(2),...liveDraftPayload(plan,config.merchantEmail).amount}}}
function anchor(){return{id:config.anchorId,status:'DRAFT',invoicer:{email_address:config.merchantEmail},detail:{reference:'AH-A6-B183',currency_code:'USD'},amount:{currency_code:'USD',value:'16.28'}}}
function mock(responses){const calls=[];return{calls,fetch:async(u,o)=>{calls.push([u,o]);if(u.endsWith('/v1/oauth2/token'))return Response.json({access_token:'SYNTHETIC'});let r=responses.shift();if(!r)throw Error('unexpected');return r instanceof Response?r:Response.json(r)}}}
test('Live payload accepts verified address without email and limits October 5 PG merchandise',()=>{const q={...p,recipientEmail:undefined};assert.equal(liveDraftPayload(q,config.merchantEmail).primary_recipients[0].billing_info.email_address,undefined);assert.throws(()=>liveDraftPayload({...p,reference:'AH-A4-B145'},config.merchantEmail));assert.throws(()=>liveDraftPayload({...p,discountCents:150,dueCents:1850},config.merchantEmail));const member=liveDraftPayload({...p,reference:'AH-A6-B142',discountCents:150,dueCents:1850},config.merchantEmail);assert.equal(member.amount.breakdown.discount.invoice_discount.amount.value,'1.50');assert.equal(member.detail.invoice_date,undefined);assert.equal(member.configuration.allow_tip,false)})
test('approved manifest requires exact hash and rejects edits or duplicate buyers',()=>{const raw=JSON.stringify([p]),hash=crypto.createHash('sha256').update(raw).digest('hex');assert.equal(validateLiveManifest(raw,hash,config.merchantEmail)[0].reference,p.reference);assert.throws(()=>validateLiveManifest(raw+' ',hash,config.merchantEmail));const dup=JSON.stringify([p,p]);assert.throws(()=>validateLiveManifest(dup,crypto.createHash('sha256').update(dup).digest('hex'),config.merchantEmail))})
test('known native draft is read and reused with zero invoice POSTs',async()=>{const m=mock([anchor(),inv()]);const r=await createLiveDraftAdapter(config,m.fetch).createDraft({...p,existingInvoiceId:'INV2-SYNTHETIC-0001'});assert.equal(r.reused,true);assert.equal(m.calls.filter(([u,o])=>o.method==='POST'&&!u.endsWith('/token')).length,0)})
test('new draft lists invoices before creating and verifies DRAFT exact amount; no send or payment endpoints exist',async()=>{const m=mock([anchor(),{total_pages:1,items:[]},inv(),inv()]);const adapter=createLiveDraftAdapter(config,m.fetch);const r=await adapter.createDraft(p);assert.equal(r.status,'DRAFT');assert.equal(r.totalCents,2000);assert.deepEqual(Object.keys(adapter).sort(),['createDraft','reconcile']);const writes=m.calls.filter(([u,o])=>o.method==='POST'&&!u.endsWith('/token'));assert.equal(writes.length,1);assert.equal(writes[0][0],'https://api-m.paypal.com/v2/invoicing/invoices');assert.equal(m.calls.every(([u])=>new URL(u).origin==='https://api-m.paypal.com'),true);assert.equal(JSON.parse(writes[0][1].body).detail.invoice_number,p.reference)})
test('wrong merchant, SENT status, duplicate references and uncertain create stop without another write',async()=>{const wrong=mock([{...anchor(),invoicer:{email_address:'other@example.invalid'}}]);await assert.rejects(createLiveDraftAdapter(config,wrong.fetch).createDraft(p),/merchant/);assert.equal(wrong.calls.length,2);const duplicate=mock([anchor(),{total_pages:1,items:[inv(),inv()]}]);await assert.rejects(createLiveDraftAdapter(config,duplicate.fetch).createDraft(p),/Duplicate/);const sent=mock([anchor(),{...inv(),status:'SENT'}]);await assert.rejects(createLiveDraftAdapter(config,sent.fetch).createDraft({...p,existingInvoiceId:'INV2-SYNTHETIC-0001'}),/status/);const uncertain=mock([anchor(),{total_pages:1,items:[]},new Response('SYNTHETIC SECRET',{status:500})]);await assert.rejects(createLiveDraftAdapter(config,uncertain.fetch).createDraft(p),e=>!e.message.includes('SECRET')&&e.message.includes('uncertain'));assert.equal(uncertain.calls.filter(([u,o])=>o.method==='POST'&&!u.endsWith('/token')).length,1)})
