const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript')
test('private invoice runtime requires Sandbox, isolated database and exact private callback before adapter construction',()=>{
 const values={VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'feature/private-invoices',AUCTION_PAYPAL_CHECKOUT_ENABLED:'true',PAYPAL_ENVIRONMENT:'sandbox',DATABASE_URL:'postgresql://fixture:unused@ep-withered-queen-aqf01v2f-pooler.c-8.us-east-1.aws.neon.tech/auction_invoice_sandbox',PAYPAL_RETURN_URL:'https://smallbizzwizz-git-feature-privat-e042a5-blake-schmitts-projects.vercel.app/auction/paypal/return',PAYPAL_CANCEL_URL:'https://smallbizzwizz-git-feature-privat-e042a5-blake-schmitts-projects.vercel.app/auction/paypal/return?cancel=1',PAYPAL_WRITES_ENABLED:'true',PAYPAL_CLIENT_ID:'synthetic-unused',PAYPAL_CLIENT_SECRET:'synthetic-unused',PAYPAL_MERCHANT_ID:'synthetic-unused'},old=Object.fromEntries(Object.keys(values).map(k=>[k,process.env[k]]))
 let calls=0;const mod={exports:{}},source=fs.readFileSync(path.join(__dirname,'../lib/paypal-runtime.ts'),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText
 new Function('require','module','exports',code)(name=>{assert.equal(name,'./paypal-orders-adapter');return{createPayPalOrdersAdapter:config=>{calls++;return config}}},mod,mod.exports)
 try{
  Object.assign(process.env,values);const config=mod.exports.configuredPayPalAdapter();assert.equal(config.environment,'sandbox');assert.equal(config.writesEnabled,true);assert.equal(calls,1)
  for(const [key,value] of [['VERCEL_ENV','production'],['PAYPAL_ENVIRONMENT','live'],['DATABASE_URL','postgresql://fixture:unused@ep-withered-queen-aqf01v2f-pooler.c-8.us-east-1.aws.neon.tech/neondb'],['DATABASE_URL','postgresql://fixture:unused@other.example.invalid/auction_invoice_sandbox'],['PAYPAL_RETURN_URL','https://smallbizzwizz.com/auction/paypal/return'],['PAYPAL_CANCEL_URL','https://smallbizzwizz-git-feature-privat-e042a5-blake-schmitts-projects.vercel.app/wrong']]){Object.assign(process.env,values);process.env[key]=value;assert.throws(()=>mod.exports.configuredPayPalAdapter(),/Private invoice rehearsal/);assert.equal(calls,1)}
  Object.assign(process.env,values);process.env.AUCTION_PAYPAL_CHECKOUT_ENABLED='false';assert.throws(()=>mod.exports.configuredPayPalAdapter(),/not enabled/);assert.equal(calls,1)
 }finally{for(const key of Object.keys(values))old[key]===undefined?delete process.env[key]:process.env[key]=old[key]}
})
