import type {BillPublicView} from './auction-bill-model'
import {checkoutMatches} from './customer-invoice-policy'
export const billSecurityHeaders={'Cache-Control':'private, no-store, max-age=0','Referrer-Policy':'no-referrer','X-Robots-Tag':'noindex, nofollow, noarchive','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",'Content-Type':'text/html; charset=utf-8'}
const escape=(v:unknown)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')
const money=(n:number)=>'$'+(n/100).toFixed(2)
export function renderPrivateBill(v:BillPublicView|null,checkoutPath?:string){
if(!v)return '<h1>This invoice link is unavailable</h1>'
const payable=['unpaid','partial'].includes(v.status)&&!v.reviewMode;
const options=payable?(v.checkoutOptions||[]).filter(o=>checkoutMatches(o,v.reference,v.outstandingCents)):[];
const checkout=payable&&checkoutPath&&/^\/auction\/bill\/[a-f0-9]{64}\/checkout$/.test(checkoutPath)?checkoutPath:null;
const state=v.status==='paid'?'Paid — thank you':v.status==='pending'?'Payment pending':v.status==='review'||v.status==='superseded'?'We’re reviewing your invoice':'Your invoice';
return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your auction invoice</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f2ee;color:#252c30;font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}.preview{text-align:center;font-size:12px;color:#776f63;padding:12px}main{max-width:560px;margin:4px auto 40px;background:white;border:1px solid #e3dfd7;border-radius:16px;padding:32px}.brand{font-size:12px;letter-spacing:.15em;font-weight:750;color:#476058}h1{font-size:29px;line-height:1.2;margin:16px 0 8px}.subtitle{color:#6b7375;margin:0 0 28px}.items{width:100%;border-collapse:collapse}.items td{padding:16px 0;border-bottom:1px solid #e9ecea}.items td:last-child{text-align:right;white-space:nowrap}.qty{color:#7b8182;font-size:13px;display:block;margin-top:3px}.summary{margin-top:24px}.row{display:flex;justify-content:space-between;gap:16px;padding:7px 0}.waiting{color:#78817d}.total{margin-top:12px;padding-top:18px;border-top:1px solid #e1e5e2;font-weight:700;font-size:20px}.message{font-size:14px;color:#626e68;background:#f1f5f2;padding:13px 16px;border-radius:8px;margin:24px 0}h2{font-size:16px;margin:28px 0 12px}.payments{display:grid;grid-template-columns:1fr 1fr;gap:12px}button{font:600 15px system-ui;border:1px solid #dde3df;border-radius:9px;padding:14px;background:#eef1ef;color:#7c8580;width:100%;cursor:default}.foot{font-size:12px;color:#89908d;text-align:center;margin:18px 0 0}@media(max-width:600px){main{margin:0 12px 24px;padding:24px;border-radius:12px}h1{font-size:27px}.total{font-size:18px}} </style><body>${v.reviewMode?'<div class="preview">Customer preview · not live</div>':''}<main><div class="brand">THE CRAFTY BROTHER</div><h1>${state}</h1><p class="subtitle">${escape(v.buyerName)} · ${escape(v.auctionTitle)}</p><table class="items"><tbody>${v.items.map(i=>'<tr><td>'+escape(i.name)+'<span class="qty">Qty 1</span></td><td>'+money(i.cents)+'</td></tr>').join('')}</tbody></table><div class="summary"><div class="row"><span>Subtotal</span><span>${money(v.subtotalCents)}</span></div>${v.membershipVerified&&v.discountCents?'<div class="row"><span>Private-group discount</span><span>−'+money(v.discountCents)+'</span></div>':''}<div class="row"><span>Shipping</span><span>${money(v.shippingCents)}</span></div>${v.creditedCents?'<div class="row"><span>Payment recorded</span><span>'+money(v.creditedCents)+'</span></div>':''}<div class="row total"><span>${v.creditedCents?'Remaining total':'Total'}</span><span>${money(v.outstandingCents)}</span></div></div><h2>Pay with</h2><div class="payments">${checkout?'<form method="post" action="'+escape(checkout)+'"><button style="background:#173f81;color:white;cursor:pointer">Pay with PayPal</button></form><button disabled>Venmo</button>':options.length?options.map(o=>'<a class="pay" href="'+escape(o.url)+'" rel="noreferrer noopener">'+escape(o.label)+'</a>').join(''):'<button disabled>PayPal</button><button disabled>Venmo</button>'}</div>${options.length||checkout?'':'<p class="foot">Payment options will be ready here soon.</p>'}</main></body></html>`
}
export function privateBillResponse(v:BillPublicView|null,checkoutPath?:string){return new Response(renderPrivateBill(v,checkoutPath),{status:v?200:404,headers:billSecurityHeaders})}
