import {createHash} from 'node:crypto'

export type LiveDraftPlan={reference:string;buyerName:string;recipientEmail?:string;address:{address_line_1:string;address_line_2?:string;admin_area_2:string;admin_area_1:string;postal_code:string;country_code:string};items:{name:string;quantity:number;unitCents:number}[];subtotalCents:number;discountCents:number;shippingCents:number;dueCents:number;existingInvoiceId?:string}
type Money={currency_code?:string;value?:string}
type ProviderInvoice={id?:string;status?:string;detail?:{invoice_number?:string;reference?:string;note?:string;currency_code?:string};invoicer?:{email_address?:string};primary_recipients?:{billing_info?:{name?:{full_name?:string};email_address?:string;address?:LiveDraftPlan['address']}}[];items?:{name?:string;quantity?:string;unit_amount?:Money}[];amount?:Money&{breakdown?:{shipping?:{amount?:Money};discount?:{invoice_discount?:{amount?:Money;percent?:string}}}}}
export type LiveDraftConfig={clientId:string;clientSecret:string;merchantEmail:string;anchorId:string;enabled:boolean}
const base='https://api-m.paypal.com'
const buyerIds=new Set([135,136,137,138,140,141,142,144,145,146,148,149,151,155,163,173,174,180,183,184,189,192,194,195,198,201,204,205,206,191])
function id(value:string){if(!/^INV2-[A-Z0-9-]{8,60}$/.test(value))throw Error('Invalid invoice ID');return value}
function dollars(value:number){if(!Number.isSafeInteger(value)||value<0||value>100000000)throw Error('Invalid reviewed amount');return(value/100).toFixed(2)}
function money(value:Money|undefined,zero=false){if(!value&&zero)return 0;if(value?.currency_code!=='USD'||!value.value||!/^[-]?\d{1,8}\.\d{2}$/.test(value.value))throw Error('Unexpected provider currency or amount');return Math.round(Number(value.value)*100)}
export function liveDraftPayload(p:LiveDraftPlan,merchantEmail:string){
 const buyer=Number(/^AH-A6-B(\d+)$/.exec(p.reference)?.[1]);if(!buyerIds.has(buyer)||!p.buyerName?.trim()||!/^\S+@\S+\.\S+$/.test(merchantEmail))throw Error('Unapproved auction or merchant');
 if(p.recipientEmail&&!/^\S+@\S+\.\S+$/.test(p.recipientEmail))throw Error('Invalid reviewed recipient');
 if(!p.address||p.address.country_code!=='US'||['address_line_1','admin_area_2','admin_area_1','postal_code'].some(k=>!String(p.address[k as keyof typeof p.address]??'').trim()))throw Error('Verified US recipient address required');
 if(!Array.isArray(p.items)||!p.items.length||p.items.length>100||p.items.some(i=>!i.name?.trim()||i.name.length>200||!Number.isSafeInteger(i.quantity)||i.quantity<1||i.quantity>10000))throw Error('Invalid reviewed items');
 for(const i of p.items)dollars(i.unitCents);for(const n of[p.subtotalCents,p.discountCents,p.shippingCents,p.dueCents])dollars(n);
 const discount=[142,205].includes(buyer)?Math.round(p.subtotalCents*.1):0;
 if(p.items.reduce((n,i)=>n+i.unitCents*i.quantity,0)!==p.subtotalCents||p.discountCents!==discount||p.dueCents!==p.subtotalCents-discount+p.shippingCents||p.dueCents<=0)throw Error('Reviewed invoice totals or PG discount differ');
 return{detail:{invoice_number:p.reference,reference:p.reference,currency_code:'USD',payment_term:{term_type:'DUE_ON_RECEIPT'},note:p.reference+' — October 5 auction. '+(discount?'10% private-group discount applies to merchandise only.':'Reviewed merchandise and shipping.')},invoicer:{email_address:merchantEmail},primary_recipients:[{billing_info:{name:{full_name:p.buyerName},...(p.recipientEmail?{email_address:p.recipientEmail}:{}),address:p.address}}],items:p.items.map(i=>({name:i.name,quantity:String(i.quantity),unit_amount:{currency_code:'USD',value:dollars(i.unitCents)},unit_of_measure:'QUANTITY'})),configuration:{allow_tip:false,partial_payment:{allow_partial_payment:false},tax_inclusive:false},amount:{breakdown:{shipping:{amount:{currency_code:'USD',value:dollars(p.shippingCents)}},...(discount?{discount:{invoice_discount:{amount:{currency_code:'USD',value:dollars(discount)}}}}:{})}}};
}
export function validateLiveManifest(raw:string,expectedHash:string,merchantEmail:string){
 if(raw.length>200000||!/^\w{64}$/.test(expectedHash)||createHash('sha256').update(raw).digest('hex')!==expectedHash)throw Error('Manifest does not match the approved review');
 let plans:LiveDraftPlan[];try{plans=JSON.parse(raw)}catch{throw Error('Invalid reviewed manifest')};if(!Array.isArray(plans)||!plans.length||plans.length>30||new Set(plans.map(p=>p.reference)).size!==plans.length)throw Error('Invalid reviewed buyer list');for(const p of plans)liveDraftPayload(p,merchantEmail);return plans;
}
export function createLiveDraftAdapter(config:LiveDraftConfig,transport:typeof fetch=fetch){
 if(!config.enabled||!config.clientId||!config.clientSecret||!/^\S+@\S+\.\S+$/.test(config.merchantEmail))throw Error('Live draft-only connection is not configured');id(config.anchorId);
 let access:string|undefined;
 async function request(path:string,method:'GET'|'POST',payload?:unknown):Promise<Record<string,any>>{
  const valid=(method==='GET'&&(/^\/v2\/invoicing\/invoices\/INV2-[A-Z0-9-]{8,60}$/.test(path)||/^\/v2\/invoicing\/invoices\?page=\d+&page_size=100&total_required=true$/.test(path)))||(method==='POST'&&path==='/v2/invoicing/invoices');if(!valid)throw Error('Provider operation is outside draft-only scope');
  try{
   if(!access){const r=await transport(base+'/v1/oauth2/token',{method:'POST',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:'Basic '+Buffer.from(config.clientId+':'+config.clientSecret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!r.ok)throw Error();const token=await r.json();if(typeof token.access_token!=='string'||!token.access_token)throw Error();access=token.access_token;}
   const r=await transport(base+path,{method,redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+access,'Content-Type':'application/json',Prefer:'return=representation'},...(payload?{body:JSON.stringify(payload)}:{})});if(!r.ok)throw Error();return await r.json();
  }catch{throw Error('Live draft request failed or is uncertain; stop and reconcile before creating again')}
 }
 function merchant(invoice:ProviderInvoice){if(invoice.invoicer?.email_address?.toLowerCase()!==config.merchantEmail.toLowerCase()||invoice.detail?.currency_code!=='USD')throw Error('Existing Live merchant or currency differs from review')}
 async function verifyAccount(){const anchor=await request('/v2/invoicing/invoices/'+config.anchorId,'GET') as ProviderInvoice;merchant(anchor);if(anchor.id!==config.anchorId||anchor.status!=='DRAFT'||!hasReference(anchor,'AH-A6-B183')||money(anchor.amount)!==1628)throw Error('Existing Tonya draft account check failed');}
 function hasReference(i:ProviderInvoice,reference:string){return i.detail?.reference===reference||i.detail?.invoice_number===reference||new RegExp('(?:^|[^A-Za-z0-9-])'+reference+'(?:$|[^A-Za-z0-9-])').test(i.detail?.note??'')}
 async function list(){const all:ProviderInvoice[]=[];for(let page=1;page<=1000;page++){const r=await request('/v2/invoicing/invoices?page='+page+'&page_size=100&total_required=true','GET');if(!Array.isArray(r.items)||!Number.isInteger(r.total_pages)||r.total_pages<0||r.total_pages>1000)throw Error('Complete invoice reconciliation is unavailable');all.push(...r.items);if(page>=r.total_pages)return all;}throw Error('Invoice reconciliation limit reached');}
 function match(i:ProviderInvoice,p:LiveDraftPlan){merchant(i);if(i.status!=='DRAFT'||!hasReference(i,p.reference)||money(i.amount)!==p.dueCents||money(i.amount?.breakdown?.shipping?.amount,true)!==p.shippingCents)throw Error('Existing invoice status, reference or total requires review');const d=i.amount?.breakdown?.discount?.invoice_discount;const discount=d?.amount?Math.abs(money(d.amount)):d?.percent?Math.round(p.subtotalCents*Number(d.percent)/100):0;if(discount!==p.discountCents)throw Error('Existing invoice discount differs');const r=i.primary_recipients?.[0]?.billing_info;if(i.primary_recipients?.length!==1||!r||r.name?.full_name?.trim().toLowerCase()!==p.buyerName.trim().toLowerCase()||(p.recipientEmail&&r.email_address?.toLowerCase()!==p.recipientEmail.toLowerCase()))throw Error('Existing invoice recipient differs');if(p.address.address_line_1!==r.address?.address_line_1||p.address.postal_code!==r.address?.postal_code)throw Error('Existing invoice address differs');if(i.items?.length!==p.items.length||i.items.some((v,n)=>v.name!==p.items[n].name||Number(v.quantity)!==p.items[n].quantity||money(v.unit_amount)!==p.items[n].unitCents))throw Error('Existing itemization differs');return{reference:p.reference,invoiceId:id(i.id??''),status:'DRAFT' as const,totalCents:p.dueCents,merchantReviewUrl:'https://www.paypal.com/invoice/s/details/'+id(i.id??'')};}
 async function reconcile(p:LiveDraftPlan){liveDraftPayload(p,config.merchantEmail);await verifyAccount();if(p.existingInvoiceId)return match(await request('/v2/invoicing/invoices/'+id(p.existingInvoiceId),'GET') as ProviderInvoice,p);const candidates=(await list()).filter(i=>hasReference(i,p.reference));if(candidates.length>1)throw Error('Duplicate stable reference requires review');return candidates.length?match(await request('/v2/invoicing/invoices/'+id(candidates[0].id??''),'GET') as ProviderInvoice,p):null;}
 return{reconcile,async createDraft(p:LiveDraftPlan){const existing=await reconcile(p);if(existing)return{...existing,reused:true};const payload=liveDraftPayload(p,config.merchantEmail);const result=await request('/v2/invoicing/invoices','POST',payload);let invoiceId=result.id;if(!invoiceId&&typeof result.href==='string'){const u=new URL(result.href);if(u.origin!==base||!/^\/v2\/invoicing\/invoices\/INV2-[A-Z0-9-]{8,60}$/.test(u.pathname))throw Error('Unexpected Live invoice reference');invoiceId=u.pathname.split('/').pop()}const savedId=id(invoiceId??'');try{return{...match(await request('/v2/invoicing/invoices/'+savedId,'GET') as ProviderInvoice,p),reused:false}}catch{throw Error('Draft created as '+savedId+'; readback requires reconciliation. Do not create another invoice.')}}};
}
